### ISSUE TITLE
App Icon for [APP]

### ISSUE THREAD

**Issue by F0lkl0re** [JDagsa/JDagsa.github.io#2]
### App Name
Foupon
Google Classroom
Google Hangouts
Google Photos
Soundcorset
Apollo
Pager

### Bundle Identifier
co.foupon.foupon
com.google.Classroom
com.google.hangouts
com.google.photos
com.soundcorset.client.ios
com.christianselig.Apollo
com.joshuat.pagerapp

**Comment by JDagsa** [comment]
Ok, I already have some of these on the list. These include:

- Google Photos
- Apollo

I'll work on them. Thanks @F0lkl0re!

**Comment by JDagsa** [comment]
Ok @F0lkl0re , the icons you have requested have been themed, and will come in the next release of BSE, v1.0.0.

Thank you so much!

~ Jayden
